apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service-serviceaccount
  namespace: auction
  annotations:
    iam.gke.io/gcp-service-account: notification-service@realtime-auction-service.iam.gserviceaccount.com
