apiVersion: v1
kind: Service
metadata:
  name: notification-service-service
  namespace: auction
  labels:
    monitoring: prometheus
spec:
  selector:
    app: notification-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
