apiVersion: v1
kind: Service
metadata:
  name: notification-service-service
  namespace: auction
spec:
  selector:
    app: notification-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
    - name: ws
      port: 8084
      targetPort: 8084
      protocol: TCP
