apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets-system
  annotations:
    # Workload Identity: GCP Secret Manager 접근용 GCP SA 바인딩
    iam.gke.io/gcp-service-account: external-secrets-sa@realtime-auction-service.iam.gserviceaccount.com
