---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgATI3mJrtjfEX4mEsV+NFwtlM1DjcKPlQ4ACDaL0c4QgBf89djdnFLE2Z9HNk5gRyzqnvWSFY07cK9mKK8wsbVnY0q9U/kfGNZnUl9nrbpjlAhI7X1N0VIgBTOIznXAAZ/BmHOukCgQJ7mMYocOA0qQxxvKvvf21syPYFuLfR8BB5IbQmCX+MGv3KgVCeCFGxENpp1QfRcvwTZJxA6BRC6tY8Wg7/OJP0F+SCEA3ulgBkaZp/Ce7A5SKmM3bwVTeloROaQvb+AoRDFaYeh2z+D2SkBTN+I0B9FIf3hIjV7P7m5uYZdGIlvscue0MspHEhxg/1Vqn75o5cmhrTht3OQN7MXVzyRrmg/qo3J+fLnH+baklVLuBOY0yXMa4Cvuf3qSYOMPwb4vYKmv1CgLQFiQa5B9zYSOpEoJvmXndqhrmivaIhyNfn8QYlGZ9W+XNP+VD/yzAE6+Wfc22+TAVoKrQ6BQAbu+akME2UnCu+V6lypzu5iPXWZwc8TugJeLU9cvaI8NogkfE4PFXKgU4KU4g6YY9fIxSEvYOKc1QnM7IN58aEhE/+ilfVU3wKlGpdB3KzDa6Yt/bF+EFiS9JbbsQUOIsxsiEutKVUkTi2ch1nZ5tznS/v/QlnoHOtQ4Pj1BvC5lxPRLlTJhKrFnqts3R33E0FLwxjC3yg9rgtmy8kk7cyrbC5quC4OeAmvv+g4jSlEvrIwyOvk=
    admin-user: AgBn3LGpvG4NKAf/VHrmgQUBWs1gEW4pV/OCR73ofpsZh+VaOQxvzVtecVNx5lFrcsQKsPZW1RStlapKnQNwLN2HLqT0SqqtcFFYlhJUFIc9Nne9oVxa2BbRqB3Z3LEeyKR/nULdEBathMjVLzvhCRbRUuvotnuOyyZekm7dlL3VR0kpsK8kStCGxh4M8sjL2B3nqUFRBGnnh06WXkW+4udZR+MEEsO8Tzc3rzDD2Pkg/uAvwFeHmNRTe4ANtwI2n0hSXGtI8iPoOHWZfPtOiTYMlFPfp5SRlYTQzHcigzL5nBS5kmaJQ3FneF6+bgJEoLAkAYpZaFAmJD7IE2g9A49EXHYVpIXUhlbO4eitjkLdQyTHHaQWgWonax1pdXp9/+91VGHAPy7AlVMm61+UYWxODigMr2xijiSUFeqbnlCQaDmJgzhwg3lj6/B1lfs9cc7DOmEF/5LRKOrOnILAgmU6KrW3pv0UukBUAF1JU3ouK0thtTviyDOy4aeDauhEheUA6cRM8nz45OCbLunEjfSQPC7Ovqub68rQdNarKjvdrPjQe2c0ybu3F0eSEKqNAZQMQvf2u9cZeREt4Oft7wCGZSUD53zJO+07jy/9J2iErCYzBVvVhmpzZYYI+skF2SE+SJPqsHNXWnSrrInNSfGNx2UZxAIp35iMX3JfsGTTGAbJ9crbJM1vMxX/vDyJWxQiyovPWA==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
