---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-minio-secret
  namespace: monitoring
spec:
  encryptedData:
    rootPassword: AgBfBcONDo8l8xoJq6HQQSrNgJqmo+GEvdxUzTm+ofGNyL/tI0f0HvTYWgfuihXKHhhFJyaAQ5G0oHyXJnJNs3ddx+BrtxDiGq9gWKdIc2qHIIGfwX+YSiJwJYK11pRmPB5xnJ1x3NZlf0u5bkBSMPrIQ8TqB0EnHVsHqwbvue4QwQAa0f73yHPwatGiyeETj8MHMkEmBuPbdUrKpMwB4kQfydgcVEmdJxx5OiIdCGvwILPvQgl0ET7LnJi+HVwXtt7lsQ73s0O4VY6GouJmCR/SSC1MZPDkFyeI0Nm7T0Z7m8TiTbEGzosWLv79H9oXUBln13k+Uxs527XYYRwe2RY90Y+KqGPAvrNFveqnfQGyMc/NZu020eRE3cImw6QP/kJennlnwa2q/Muf3KkzLR/PQNjV3NB/7SmmbocGtuE/LNfdINOiJT/Ko0X6ghJKlQJDaGMk/haI1Uiam07RE0ldoEcdY1/dND+ESnVGpIMPAO2sXZxKO3ZkvjAufq94M3HkSVB8BZvwm577ZhHqgjBnUnIBwinxg8OQxv1S/7EY3lbkyRneJXTSgjpjtvaxBwLk3H9ND09+z4x6mPGHJcNI8Cc6lP0YgZ5PdgEmG1u+vPWT3fYqXGx6bw4T42FboSPZHLGAA+3HTVDp1h5wh50j0PH5cxfNNhk6SPwXn+C9/i2/kaM09fhr6+ct/LMvaIevCGQIoRH4dZXlbxbxX47nufHCiKrqH8A2ZEoBUM5XBg==
    rootUser: AgBVLc4vXlgnurRuXTmlu/jKHk5bnyS4n+KgulCiEeDFVZOVwemkMmzHOAdBY16ypk7hZiEhHj/Q3uQ5bfv/29vcsktcDy2OPTzWwD/ZNjAW4H6dIzhdzYdtCy7qYTr+R6qPT/oG/3rlynBMWiVWHJ+hvE8DqNK/eW5N1u/C/qZNWeEX0Oj1uyAQIsysktIJraaERHF4CDSR5+GtheFjlRBMyle7LXTCrDyQA16eDbKVqxhl6pLRZp9qJa+g5ZV6qy2fu+2DraCqnhTPMgvG6K6atA3pIftAa9R44tBIsktzhjlHAF3FIfpe276Lqjnv2JlrHmnhvJE0buaBLvPI7nsA29cPg8EDARQuwZC+ZIzaS0UnyvS7/DZkD2Xa60yqxqfaMhuewZQKxGIpF2a68O0jiuEze0ScZsrLzaDu+CelqjwgU4lgg3C4Y8ztdxbcFU4Eb3/nCUVqpkiuoqex1tEXjA3ieNeo0qgAYvHsQOhrtmtLW4vWMzQ7GJHF+TAEiWT/0sfhlmEJhV+Q76UnpmIXn6CMxZ3nVWlxupAtrVUgYJNToM1DAUtgtjRCOLa49/HCrthl5KOT99sXPJpJ69Uy+jC4K+dhBL9dSmzVvdpq5jx5CTORIjCMX8QtG23hvND18Izk5+mAW3Ee9vRGPkWIO7ddSvnaNv4+tbO/5WvM42p6VQjBFtZPFw1/ej0NkMgglwvX
  template:
    metadata:
      name: loki-minio-secret
      namespace: monitoring
