apiVersion: v1
kind: ConfigMap
metadata:
  name: debezium-configmap
  namespace: auction
data:
  BOOTSTRAP_SERVERS: auction-kafka-kafka-bootstrap:9092
  GROUP_ID: debezium-connect
  CONFIG_STORAGE_TOPIC: debezium-configs
  OFFSET_STORAGE_TOPIC: debezium-offsets
  STATUS_STORAGE_TOPIC: debezium-status
  CONFIG_STORAGE_REPLICATION_FACTOR: "2"
  OFFSET_STORAGE_REPLICATION_FACTOR: "2"
  STATUS_STORAGE_REPLICATION_FACTOR: "2"
  CONNECT_REST_PORT: "8083"
  CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
  CONNECT_VALUE_CONVERTER: io.confluent.kafka.serializers.KafkaAvroConverter
  CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
  CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry-service:8085
  # 각 DB 에 대한 Cloud SQL Auth Proxy 연결 이름
  # auction-db 프록시: localhost:5432, bid-db 프록시: localhost:5433
  AUCTION_CLOUD_SQL_CONNECTION_NAME: PROJECT_ID:asia-northeast3:auction-db
  BID_CLOUD_SQL_CONNECTION_NAME: PROJECT_ID:asia-northeast3:bid-db
