apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: debezium-externalsecret
  namespace: auction
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: debezium-secret
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: debezium-postgres-user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: debezium-postgres-password
