apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: auction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      serviceAccountName: api-gateway-serviceaccount
      tolerations:
        - key: "spot"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      containers:
        - name: api-gateway
          image: api-gateway
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-gateway-configmap
          env:
            - name: OTEL_SERVICE_NAME
              value: api-gateway
            - name: INTERNAL_REQUEST_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secret
                  key: INTERNAL_REQUEST_SECRET
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secret
                  key: JWT_PUBLIC_KEY
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
