apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-gateway-externalsecret
  namespace: auction
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: api-gateway-secret
  data:
    - secretKey: INTERNAL_REQUEST_SECRET
      remoteRef:
        key: internal-request-secret
    - secretKey: JWT_PUBLIC_KEY
      remoteRef:
        key: jwt-public-key
