apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-serviceaccount
  namespace: auction
  annotations:
    # Workload Identity: GKE SA와 GCP SA를 바인딩
    iam.gke.io/gcp-service-account: api-gateway@realtime-auction-service.iam.gserviceaccount.com
