apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/user-service
  # CD 파이프라인(cd.yml)이 newTag를 SHORT_SHA로 갱신한다
images:
- name: user-service
  newName: asia-northeast3-docker.pkg.dev/realtime-auction-service/auction-images/user-service
  newTag: 319faad
patches:
- path: configmap-patch.yaml
