apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/debezium
images:
  - name: asia-northeast3-docker.pkg.dev/realtime-auction-service/auction-images/debezium-connect
    newTag: latest
patches:
  - path: configmap-patch.yaml
  - path: connector-configmap-patch.yaml
