apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auction-streams
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: auction-project
  source:
    repoURL: https://github.com/jaehoon9875/realtime-auction-service
    targetRevision: feature/m8-gke-deployment
    path: infra/k8s/overlays/dev/auction-streams
  destination:
    server: https://kubernetes.default.svc
    namespace: auction
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
