apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: auction-events
  namespace: auction
  labels:
    strimzi.io/cluster: auction-kafka
spec:
  partitions: 3
  replicas: 2
  config:
    retention.ms: "604800000"
    cleanup.policy: delete
