apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: bid-events
  namespace: auction
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    strimzi.io/cluster: auction-kafka
spec:
  partitions: 3
  replicas: 2
  config:
    retention.ms: "604800000"
    cleanup.policy: delete
