apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace/
  - kafka/
  - schema-registry/
  - debezium/
  - api-gateway/
  - auction-service/
  - bid-service/
  - user-service/
  - notification-service/
  - auction-streams/
