apiVersion: v1
kind: ConfigMap
metadata:
  name: auction-streams-configmap
  namespace: auction
data:
  AUCTION_STREAMS_PORT: "PLACEHOLDER"
  KAFKA_BOOTSTRAP_SERVERS: PLACEHOLDER
  KAFKA_STREAMS_APPLICATION_ID: PLACEHOLDER
  SCHEMA_REGISTRY_URL: PLACEHOLDER
  KAFKA_STREAMS_STATE_DIR: PLACEHOLDER
  AUCTION_STREAMS_PUNCTUATOR_INTERVAL_SECONDS: "PLACEHOLDER"
  AUCTION_STREAMS_MAX_FAILURES: "PLACEHOLDER"
  AUCTION_STREAMS_IQ_PEER_CONNECT_TIMEOUT_MS: "PLACEHOLDER"
  AUCTION_STREAMS_IQ_PEER_READ_TIMEOUT_MS: "PLACEHOLDER"
