apiVersion: v1
kind: ServiceAccount
metadata:
  name: auction-streams-serviceaccount
  namespace: auction
  annotations:
    iam.gke.io/gcp-service-account: auction-streams@PROJECT_ID.iam.gserviceaccount.com
