apiVersion: v1
kind: Service
metadata:
  name: auction-streams-service
  namespace: auction
  labels:
    monitoring: prometheus
spec:
  selector:
    app: auction-streams
  ports:
    - name: http
      port: 8086
      targetPort: 8086
