# CD 파이프라인(cd.yml)이 newTag를 SHORT_SHA로 갱신한다
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: api-gateway
  newName: asia-northeast3-docker.pkg.dev/realtime-auction-service/auction-images/api-gateway
  newTag: 8466d37
- name: auction-service
  newName: asia-northeast3-docker.pkg.dev/realtime-auction-service/auction-images/auction-service
  newTag: 8466d37
- name: auction-streams
  newName: asia-northeast3-docker.pkg.dev/realtime-auction-service/auction-images/auction-streams
  newTag: 8466d37
- name: bid-service
  newName: asia-northeast3-docker.pkg.dev/realtime-auction-service/auction-images/bid-service
  newTag: 8466d37
- name: notification-service
  newName: asia-northeast3-docker.pkg.dev/realtime-auction-service/auction-images/notification-service
  newTag: 8466d37
- name: user-service
  newName: asia-northeast3-docker.pkg.dev/realtime-auction-service/auction-images/user-service
  newTag: 8466d37
