apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auction-service-externalsecret
  namespace: auction
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: auction-service-secret
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: auction-db-password
    - secretKey: INTERNAL_REQUEST_SECRET
      remoteRef:
        key: internal-request-secret
