apiVersion: v1
kind: ServiceAccount
metadata:
  name: auction-service-serviceaccount
  namespace: auction
  annotations:
    iam.gke.io/gcp-service-account: auction-service@PROJECT_ID.iam.gserviceaccount.com
