apiVersion: v1
kind: Service
metadata:
  name: auction-service-service
  namespace: auction
spec:
  selector:
    app: auction-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
