apiVersion: v1
kind: Service
metadata:
  name: bid-service-service
  namespace: auction
  labels:
    monitoring: prometheus
spec:
  selector:
    app: bid-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
