apiVersion: v1
kind: ServiceAccount
metadata:
  name: bid-service-serviceaccount
  namespace: auction
  annotations:
    iam.gke.io/gcp-service-account: bid-service@realtime-auction-service.iam.gserviceaccount.com
