apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-registry-configmap
  namespace: auction
data:
  SCHEMA_REGISTRY_HOST_NAME: schema-registry-service
  SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8085
  SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: auction-kafka-kafka-bootstrap:9092
  SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
  SCHEMA_REGISTRY_DEBUG: "false"
