apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-registry-configmap
  namespace: auction
data:
  SCHEMA_REGISTRY_HOST_NAME: PLACEHOLDER
  SCHEMA_REGISTRY_LISTENERS: PLACEHOLDER
  SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLACEHOLDER
  SCHEMA_REGISTRY_KAFKASTORE_TOPIC: PLACEHOLDER
  SCHEMA_REGISTRY_DEBUG: "PLACEHOLDER"
