apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry-deployment
  namespace: auction
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:8.1.0
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: schema-registry-configmap
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /
              port: 8085
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
