apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service-serviceaccount
  namespace: auction
  annotations:
    iam.gke.io/gcp-service-account: user-service@realtime-auction-service.iam.gserviceaccount.com
