apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service-serviceaccount
  namespace: auction
  annotations:
    iam.gke.io/gcp-service-account: user-service@PROJECT_ID.iam.gserviceaccount.com
